name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:  # This grants necessary permissions
      contents: write  # Allow writing to the repository
      pages: write     # Allow writing to GitHub Pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure using the correct Node.js version

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: |
          cd portfolioFrontend
          npm install

      - name: Build
        run: |
          cd portfolioFrontend
          ng build --configuration production --base-href /Portfolio/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
          publish_dir: ./portfolioFrontend/dist/portfolio  # Ensure this path is correct
          publish_branch: gh-pages  # Branch where files will be published
