name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: |
          cd portfolioFrontend
          npm install

      - name: Build
        run: |
          cd portfolioFrontend
          ng build --configuration production --base-href /Portfolio/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portfolioFrontend/dist/portfolio-frontend
          publish_branch: gh-pages
